blueprints:

  - stackname: 'demo-env-{env:Environment}-website'
    description: 'Static website hosted in S3'
    template: 'website.template'
    parameters:
      Domain: '{var:HostedZoneName}'
      Subdomain: 'www-{env:Environment}'
    after:
      - 'if [[ $STATUS =~ ^(UPDATE|CREATE)_COMPLETE|NO_UPDATES_PERFORMED$ ]] ; then aws s3 sync --delete content/ s3://www-tst.aoeplay.net/; fi'