blueprints:

  - stackname: 'demo-env-{env:Environment}-website'
    description: 'Static website hosted in S3'
    template: 'website.template'
    parameters:
      Domain: '{var:HostedZoneName}'
      Subdomain: 'www-{env:Environment}'
    after:
      '/^(UPDATE|CREATE)_COMPLETE|NO_UPDATES_PERFORMED$/':
        - 'aws s3 sync --delete content/ s3://www-tst.aoeplay.net/'
      '/.*/':
        - 'echo "Done deploying blueprint \"$BLUEPRINT\" to \"$STACKNAME\" (status: \"$STATUS\")"'